price_manager/blogapp/urls.py
from django.urls import path

from .views import ArticleCreateView, ArticleDetailView, ArticleListView, ArticleUpdateView

app_name = 'blogapp'

urlpatterns = [
    path('', ArticleListView.as_view(), name='article-list'),
    path('create/', ArticleCreateView.as_view(), name='article-create'),
    path('<int:pk>/', ArticleDetailView.as_view(), name='article-detail'),
    path('<int:pk>/edit/', ArticleUpdateView.as_view(), name='article-update'),
]

price_manager/price_manager/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path

from core import views
from file_manager import views as fm_views
from supplier_product_manager import views as spm_views
from main_product_manager import views as mp_views
from supplier_manager import views as sm_views
from product_price_manager import views as ppm_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/login/', views.AppLoginView.as_view(), name='login'),
    path('accounts/logout/', views.AppLogoutView.as_view(), name='logout'),

    path('', mp_views.MainPage.as_view(), name='mainproducts'),
    path('mainproduct/table_bycat/<int:category_pk>', mp_views.MainProductTableView.as_view(), name='mainproduct-table-bycat'),
    path('mainproduct/table_nocat/', mp_views.MainProductTableView.as_view(), name='mainproduct-table-nocat'),
    path('mainproduct/resolve/table_bycat/<int:category_pk>', mp_views.MainProductResolveTableView.as_view(), name='mainproductresolve-table-bycat'),
    path('mainproduct/resolve/table_nocat/', mp_views.MainProductResolveTableView.as_view(), name='mainproductresolve-table-nocat'),

    path('mainproduct/<int:id>/update', mp_views.MainProductUpdate.as_view(), name='main-product-update'),
    path('mainproduct/sync', mp_views.sync_main_products, name='mainproducts-sync'),
    path('mainproduct/<int:pk>/info', mp_views.MainProductInfo.as_view(), name='mainproduct-info'),
    path('mainproduct/<int:pk>/update', mp_views.MainProductUpdate.as_view(), name='mainproduct-update'),
    path('mainproduct/<int:pk>/resolve', mp_views.ResolveMainproduct.as_view(), name='mainproduct-resolve'),
    path('mainproduct/<int:pk>/resolve/table', mp_views.MainProductResolveTableView.as_view(), name='mainproduct-resolve-table'),
    path('mainproduct/<int:pk>/detail', mp_views.MainProductDetail.as_view(), name='mainproduct-detail'),
    path('mainproduct/<int:pk>/pricetags', ppm_views.PriceTagList.as_view(), name='pricetag-list'),
    path('mainproduct/<int:pk>/logs', mp_views.MainProductLogList.as_view(), name='mainproductlog-list'),

    # SUPPLIER WORKFRAME
    
    path('supplier/', sm_views.SupplierList.as_view(), name='supplier'),
    
    path('supplier/<int:pk>/update', sm_views.SupplierUpdate.as_view(), name='supplier-update'),
    path('supplier/<int:id>/delete/', sm_views.SupplierDelete.as_view(), name='supplier-delete'),

    path('supplier/create/', sm_views.SupplierCreate.as_view(), name='supplier-create'),
    path('supplier/<int:pk>/', spm_views.SupplierDetail.as_view(), name='supplier-detail'),

    path('supplier/<int:pk>/upload', spm_views.UploadSupplierFile.as_view(), name='supplier-upload'),
    path('supplier/<int:pk>/copytomain/<int:state>', spm_views.copy_to_main, name='supplier-copymain'),

    path('supplier/<int:pk>/settings/', spm_views.SettingList.as_view(), name='settings'),
    path('setting/<int:pk>/', spm_views.SettingUpdate.as_view(), name='setting-update'),
    path('setting/<int:pk>/table', spm_views.XMLTableView.as_view(), name='setting-table'),
    path('setting/<int:pk>/upload/<int:state>', spm_views.setting_upload, name='setting-upload'),

    path('supplier/<int:pk>/pricemanagers/', ppm_views.PriceManagerList.as_view(), name='pricemanagers'),
    path('pricemanager/<int:pk>/', ppm_views.PriceManagerUpdate.as_view(), name='pricemanager-update'),

    # path('setting/<int:id>/delete', spm_views.SettingDelete.as_view(), name='setting-delete'),
    # path('setting/<int:id>/upload/<int:f_id>/', spm_views.SettingUpdate.as_view(), name='setting-update'),

    ##################################################################################################

    path('category/autocomplete',sm_views.CategoryAutocomplete.as_view(),name='category-autocomplete'),
    
    path('currency/', sm_views.CurrencyList.as_view(), name='currency'),
    path('currency/create/', sm_views.CurrencyCreate.as_view(), name='currency-create'),
    path('currency/<int:id>/update', sm_views.CurrencyUpdate.as_view(), name='currency-update'),

    path('price-manager/', ppm_views.PriceManagerList.as_view(), name='price-manager'),
    path('price-manager/create-for/<int:pk>', ppm_views.PriceManagerCreate.as_view(), name='pricemanager-create'),
    path('price-manager/<int:id>/delete', ppm_views.PriceManagerDelete.as_view(), name='price-manager-delete'),
    
    path('pricetag/create-for/<int:pk>', ppm_views.PriceTagCreate.as_view(), name='pricetag-create'),
    path('pricetag/<int:pk>/update', ppm_views.PriceTagUpdate.as_view(), name='pricetag-update'),

    path('supplier-product/<int:id>/delete/', spm_views.delete_supplier_product, name='supplier-product-delete'),


    path('upload/<str:name>/<int:id>/', fm_views.FileUpload.as_view(), name='upload'),

    path('shopping-tabs/', views.ShoppingTabListView.as_view(), name='shopping-tab-list'),
    path('shopping-tabs/<int:pk>/', views.ShoppingTabDetailView.as_view(), name='shopping-tab-detail'),
    path('shopping-tabs/<int:pk>/delete/', views.ShoppingTabDeleteView.as_view(), name='shopping-tab-delete'),
    path('shopping-tabs/<int:tab_pk>/products/create/', views.ShoppingTabProductCreateView.as_view(), name='shopping-tab-product-create'),
    path('shopping-tabs/<int:tab_pk>/products/<int:product_pk>/edit/', views.ShoppingTabProductUpdateView.as_view(), name='shopping-tab-product-update'),
    path('shopping-tabs/<int:tab_pk>/products/<int:pk>/delete/', views.ShoppingTabProductDeleteView.as_view(), name='shopping-tab-product-delete'),
    path('shopping-tabs/select/<int:product_id>/', views.ShoppingTabSelectionView.as_view(), name='shopping-tab-select'),
    path('shopping-tabs/<int:tab_pk>/add/<int:product_id>/', views.ShoppingTabAddProductView.as_view(), name='shopping-tab-add-product'),


    path('blog/', include('blogapp.urls')),

    path("toasts/", views.toast_messages, name="toast-messages"),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

price_manager/core/models.py
from django.db import models
from main_product_manager.models import MainProduct
# Обработка заявок

class AlternateProduct(models.Model):
  name = models.CharField(verbose_name='Название',
                          null=False)
  # filter = models.JSONField(verbose_name='Фильтр',
  #                           null=True)
  main_product = models.ForeignKey(MainProduct, 
                                    verbose_name='Главный продукт',
                                    related_name='alternate_products',
                                    on_delete=models.SET_NULL,
                                    null=True,
                                    blank=True)
  class Meta:
    constraints = [models.UniqueConstraint(fields=['name', 'main_product'], name='name_main_product_constraint')]

class ShopingTab(models.Model):
  user = models.ForeignKey('auth.User',
                           verbose_name='Пользователь',
                           on_delete=models.CASCADE,
                           related_name='shoping_tabs')
  name = models.CharField(verbose_name='Название',
                          null=False)
  products = models.ManyToManyField(AlternateProduct,
                                    verbose_name='Товары',
                                    related_name='shoping_tabs')
  open = models.BooleanField(verbose_name='Открыта',
                             default=True)
  class Meta:
    verbose_name = 'Заявка'
    constraints = [models.UniqueConstraint(fields=['user', 'name'], name='user_name_constraint')]

price_manager/main_price/models.py
from django.contrib.postgres.search import SearchVectorField, SearchVector
from django.contrib.postgres.indexes import GinIndex
from django.db import models
from django.db.models import Value


class Category(models.Model):
    parent = models.ForeignKey(
        'self',
        on_delete=models.PROTECT,
        verbose_name='Подкатегория для',
        null=True,
        blank=True,
    )
    name = models.CharField(verbose_name='Название', null=False)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['parent', 'name'], name='parent_child_constraint'),
        ]
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        if self.parent:
            return f'{self.parent}>{self.name}'
        return self.name


class Manufacturer(models.Model):
    name = models.CharField(verbose_name='Производитель', unique=True)

    class Meta:
        verbose_name = 'Производитель'
        verbose_name_plural = 'Производители'

    def __str__(self):
        return self.name


class ManufacturerDict(models.Model):
    manufacturer = models.ForeignKey(
        Manufacturer,
        verbose_name='Производитель',
        related_name='md_manufacturer_ptr',
        on_delete=models.CASCADE,
    )
    name = models.CharField(verbose_name='Вариация', unique=True, null=False)

    class Meta:
        verbose_name = 'Словарь Производителя'
        verbose_name_plural = 'Словари Производителей'

    def __str__(self):
        return f'{self.name}({self.manufacturer.name})'


MP_TABLE_FIELDS = ['article', 'supplier', 'name', 'manufacturer', 'prime_cost', 'stock']
MP_CHARS = ['sku', 'article', 'name']
MP_FKS = ['supplier', 'category', 'discount', 'manufacturer', 'price_manager']
MP_DECIMALS = ['weight', 'length', 'width', 'depth']
MP_INTEGERS = ['stock']
MP_PRICES = ['prime_cost', 'wholesale_price', 'basic_price', 'm_price', 'wholesale_price_extra']
MP_MANAGMENT = ['price_updated_at', 'stock_updated_at', 'search_vector']


class MainProduct(models.Model):
    sku = models.CharField(verbose_name='Артикул товара', null=True, blank=True)
    supplier = models.ForeignKey(
        'supplier_manager.Supplier',
        verbose_name='Поставщик',
        related_name='mp_supplier_ptr',
        on_delete=models.PROTECT,
    )
    article = models.CharField(verbose_name='Артикул поставщика')
    name = models.CharField(verbose_name='Название')
    category = models.ForeignKey(
        Category,
        on_delete=models.SET_NULL,
        verbose_name='Категория',
        null=True,
        blank=True,
    )
    manufacturer = models.ForeignKey(
        Manufacturer,
        verbose_name='Производитель',
        related_name='mp_manufacturer_ptr',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
    )
    stock = models.PositiveIntegerField(verbose_name='Остаток', null=True)
    weight = models.DecimalField(verbose_name='Вес', decimal_places=1, max_digits=8, default=0)
    prime_cost = models.DecimalField(verbose_name='Себестоимость', decimal_places=2, max_digits=20, default=0)
    wholesale_price = models.DecimalField(verbose_name='Оптовая цена', decimal_places=2, max_digits=20, default=0)
    basic_price = models.DecimalField(verbose_name='Базовая цена', decimal_places=2, max_digits=20, default=0)
    m_price = models.DecimalField(verbose_name='Цена ИМ', decimal_places=2, max_digits=20, default=0)
    wholesale_price_extra = models.DecimalField(
        verbose_name='Оптовая цена доп.', decimal_places=2, max_digits=20, default=0
    )
    price_managers = models.ManyToManyField(
        'price_manager.PriceManager',
        verbose_name='Наценка',
        related_name='main_products',
        blank=True,
    )
    length = models.DecimalField(verbose_name='Длина', max_digits=10, decimal_places=2, default=0)
    width = models.DecimalField(verbose_name='Ширина', max_digits=10, decimal_places=2, default=0)
    depth = models.DecimalField(verbose_name='Глубина', max_digits=10, decimal_places=2, default=0)
    price_updated_at = models.DateTimeField(verbose_name='Последнее обновление цены', auto_now_add=True)
    stock_updated_at = models.DateTimeField(verbose_name='Последнее обновление остатка', auto_now_add=True)
    search_vector = SearchVectorField(null=True, editable=False, unique=False, verbose_name='Вектор поиска')

    class Meta:
        indexes = [GinIndex(fields=['search_vector'])]
        verbose_name = 'Главный товар'
        verbose_name_plural = 'Главный прайс'

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        MainProduct.objects.filter(pk=self.pk).update(search_vector=SearchVector('name', config='russian'))

    def __str__(self):
        return self.sku if self.sku else 'Не указан'

    def _build_search_text(self) -> str:
        parts = [
            self.name or '',
            getattr(self.category, 'name', '') or '',
            getattr(self.manufacturer, 'name', '') or '',
            self.article or '',
            self.sku or '',
        ]
        return ' '.join(p for p in parts if p)

    def rebuild_search_vector(self):
        text = self._build_search_text()
        self.search_vector = SearchVector(Value(text), config='russian')
        self.save(update_fields=['search_vector'])

price_manager/core/forms.py
from django import forms
from core.models import ShopingTab, AlternateProduct


class ShopingTabCreateForm(forms.ModelForm):
  class Meta:
    model = ShopingTab
    fields = ['name']
    labels = {
      'name': 'Название корзины',
    }
    widgets = {
      'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Например, Заказ №1'}),
    }

class ShopingTabUpdateForm(forms.ModelForm):
  class Meta:
    model = ShopingTab
    fields = ['name', 'open']
    labels = {
      'name': 'Название',
      'open': 'Открыта',
    }
    widgets = {
      'name': forms.TextInput(attrs={'class': 'form-control'}),
      'open': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
    }


class AlternateProductForm(forms.ModelForm):
  class Meta:
    model = AlternateProduct
    fields = ['name']
    labels = {
      'name': 'Название',
    }
    widgets = {
      'name': forms.TextInput(attrs={'class': 'form-control'})
    }

price_manager/main_price/forms.py
from django import forms

from main_price.models import Category, MainProduct, Manufacturer, ManufacturerDict


class ManufacturerDictForm(forms.ModelForm):
    manufacturer = forms.ModelChoiceField(
        queryset=Manufacturer.objects.all(),
        label='',
        widget=forms.HiddenInput(),
    )

    class Meta:
        model = ManufacturerDict
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        manufacturer_queryset = kwargs.pop('manufacturer_queryset', None)
        super().__init__(*args, **kwargs)
        if manufacturer_queryset is not None:
            self.fields['manufacturer'].queryset = manufacturer_queryset


class CategoryAddForm(forms.Form):
    category = forms.ModelChoiceField(
        Category.objects,
        label='Категория',
        widget=forms.Select(attrs={'class': 'form-select'}),
    )


class MainProductForm(forms.ModelForm):
    name = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control w-50'}), label='Название')

    class Meta:
        model = MainProduct
        fields = '__all__'

price_manager/core/templates/main/dep_main.html
{% extends 'base.html' %}

{% block title %}
Главная страница
{% endblock %}

{% block style %}
  .hover-wrapper {
      position: relative;
      cursor: pointer;
    }
    .hover-card {
      position: absolute;
      top: 50%;            /* drop below the cell text  */
      left: 100%;
      z-index: 9;        /* above table borders       */
      display: none;
      width: 240px;
    }
    .hover-wrapper:hover .hover-card,
    .hover-wrapper:focus .hover-card {
      display: block;
    }

    .main-page-layout {
      padding-left: 260px;
    }

    .filter-panel {
      position: fixed;
      top: 96px;
      left: 32px;
      width: 320px;
      max-height: calc(100vh - 128px);
      overflow-y: auto;
      z-index: 1030;
    }

    .filter-panel form {
      padding-bottom: 1rem;
    }

    .filter-panel .form-group + .form-group {
      margin-top: 1rem;
    }

    .table-area {
      margin-top: 2rem;
    }

    @media (max-width: 991.98px) {
      .main-page-layout {
        padding-right: 0;
      }

      .filter-panel {
        position: static;
        width: 100%;
        max-height: none;
        margin-top: 1.5rem;
        right: auto;
      }

      .table-area {
        margin-top: 1.5rem;
      }
    }
{% endblock %}

{% block body %}
<div id="mainproduct-block">
  <div class="container-fluid main-page-layout">
    {% include 'main/includes/table.html' %}
  </div>

  <div class="filter-panel card shadow-sm mt-4">
    <div class="card-body">
      <h2 class="h4">Фильтры</h2>
      <form method="get" class="form" id="main-filter-form">
        {{ filter_form.media }}

        <div id="filters-update-sink" class="d-none"></div>

        <div class="form-group mt-3">
          <label for="{{ filter_form.search.id_for_label }}">{{ filter_form.search.label }}</label>
          {{ filter_form.search }}
        </div>

        <div class="form-group mt-3">
          <label for="{{ filter_form.anti_search.id_for_label }}">{{ filter_form.anti_search.label }}</label>
          {{ filter_form.anti_search }}
        </div>


        {% if filter_form.available %}
        <div class="form-group mt-3">
          <label for="{{ filter_form.available.id_for_label }}">{{ filter_form.available.label }}</label>
          {{ filter_form.available }}
        </div>
        {% endif %}
        
        {% include 'main/includes/filter_field.html' with field=filter_form.category container_id='category-filter-container' collapse_id='category-filter-collapse' is_category=True category_tree=category_tree selected_categories=selected_categories available_options=None collapsible=False %}
        
        {% include 'main/includes/filter_field.html' with field=filter_form.manufacturer container_id='manufacturer-filter-container' collapse_id='manufacturer-filter-collapse' available_options=available_manufacturers available_options_label='Доступные производители' collapsible=False %}
        
        {% include 'main/includes/filter_field.html' with field=filter_form.supplier container_id='supplier-filter-container' collapse_id='supplier-filter-collapse' available_options=available_suppliers available_options_label='Доступные поставщики' collapsible=False %}



        <div class="mt-4 d-flex gap-2">
            <button type="submit" class="btn btn-primary flex-grow-1">
              🔍 Искать
            </button>
            <a href="{% url 'main-product-sync'%}" class="btn btn-success">
              <i class="bi bi-recycle"></i> Обновить
            </a>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock %}

{% block script %}
<script>
  document.body.addEventListener('htmx:configRequest', (evt) => {
    evt.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';
  });

  const enhanceSelect = (selector) => {
    const element = window.jQuery ? window.jQuery(selector) : null;
    if (element && element.length && element.select2) {
      element.select2({
        width: '100%',
        placeholder: element.data('placeholder') || '',
        allowClear: true,
        language: {
          noResults: () => 'Ничего не найдено',
          searching: () => 'Поиск…'
        }
      });
    }
  };

  const initDynamicFilters = () => {
    enhanceSelect('#id_supplier');
    enhanceSelect('#id_manufacturer');
  };
  
  const setToggleButtonState = (button, isExpanded) => {
    const expandedText = button.getAttribute('data-expanded-text') || button.textContent;
    const collapsedText = button.getAttribute('data-collapsed-text') || button.textContent;
    button.textContent = isExpanded ? expandedText : collapsedText;
    button.setAttribute('aria-expanded', isExpanded ? 'true' : 'false');
  };

  const initFilterToggle = (button) => {
    if (!button || button.dataset.filterToggleInitialized === 'true') {
      return;
    }

    const targetSelector = button.getAttribute('data-bs-target');
    if (!targetSelector) {
      return;
    }

    const target = document.querySelector(targetSelector);
    if (!target) {
      return;
    }

    const updateState = () => {
      const isExpanded = target.classList.contains('show');
      setToggleButtonState(button, isExpanded);
    };

    target.addEventListener('shown.bs.collapse', () => setToggleButtonState(button, true));
    target.addEventListener('hidden.bs.collapse', () => setToggleButtonState(button, false));

    updateState();

    button.dataset.filterToggleInitialized = 'true';
  };

  const initFilterToggles = () => {
    const buttons = document.querySelectorAll('[data-filter-toggle="button"]');
    buttons.forEach(initFilterToggle);
  };

  const debounce = (fn, delay = 300) => {
    let timerId;
    return (...args) => {
      if (timerId) {
        clearTimeout(timerId);
      }
      timerId = window.setTimeout(() => {
        timerId = null;
        fn(...args);
      }, delay);
    };
  };

  const getFilterForm = () => document.getElementById('main-filter-form');

  const requestTableUpdate = () => {
    if (!window.htmx) {
      return;
    }

    const form = getFilterForm();
    if (!form) {
      return;
    }

    const params = new URLSearchParams(new FormData(form));
    params.delete('page');

    const queryString = params.toString();
    const tableUrl = '{{ table_update_url|escapejs }}';
    const separator = tableUrl.includes('?') ? '&' : '?';
    const url = queryString ? `${tableUrl}${separator}${queryString}` : tableUrl;

    window.htmx.ajax('GET', url, {
      target: '#main-table-container',
      swap: 'outerHTML',
    });

    const newLocation = queryString ? `${window.location.pathname}?${queryString}` : window.location.pathname;
    window.history.replaceState({}, '', newLocation);
  };

  const scheduleTableUpdate = debounce(requestTableUpdate, 500);

  const shouldIgnoreAutoUpdate = (element) => {
    return Boolean(element && element.dataset && element.dataset.ignoreAutoUpdate === 'true');
  };

  const registerAutoUpdate = () => {
    const form = getFilterForm();
    if (!form || form.dataset.autoUpdateInitialized === 'true') {
      return;
    }

    form.addEventListener('input', (event) => {
      const target = event.target;
      if (!target) {
        return;
      }

      if (target.matches('input[type="text"], input[type="search"], textarea')) {
        if (shouldIgnoreAutoUpdate(target)) {
          return;
        }
        scheduleTableUpdate();
      }
    });

    form.addEventListener('change', (event) => {
      const target = event.target;
      if (!target) {
        return;
      }

      if (target.matches('input, select, textarea')) {
        if (shouldIgnoreAutoUpdate(target)) {
          return;
        }
        requestTableUpdate();
      }
    });

    form.dataset.autoUpdateInitialized = 'true';
  };

  const initCategoryFilterSearch = () => {
    const containers = document.querySelectorAll('[data-category-filter]');
    containers.forEach((container) => {
      if (container.dataset.categoryFilterInitialized === 'true') {
        return;
      }

      const searchInput = container.querySelector('[data-category-filter-search]');
      const tree = container.querySelector('[data-category-tree]');

      if (!searchInput || !tree) {
        return;
      }

      const getChildList = (parent) => {
        return Array.from(parent.children).find((element) => element.tagName === 'UL');
      };

      const getChildNodes = (parent) => {
        const list = getChildList(parent);
        if (!list) {
          return [];
        }
        return Array.from(list.children).filter((child) => child.matches('[data-category-node]'));
      };

      const getRootNodes = () => {
        const rootList = tree.querySelector('ul');
        if (!rootList) {
          return [];
        }
        return Array.from(rootList.children).filter((child) => child.matches('[data-category-node]'));
      };

      const filterTree = () => {
        const term = searchInput.value.trim().toLowerCase();

        if (!term) {
          tree.querySelectorAll('[data-category-node]').forEach((node) => {
            node.classList.remove('d-none');
          });
          return;
        }

        const applyFilter = (node) => {
          const name = (node.dataset.categoryName || '').toLowerCase();
          const children = getChildNodes(node);

          let hasMatchingChild = false;
          children.forEach((child) => {
            if (applyFilter(child)) {
              hasMatchingChild = true;
            }
          });

          const matchesSelf = name.includes(term);
          const shouldShow = matchesSelf || hasMatchingChild;
          node.classList.toggle('d-none', !shouldShow);
          return shouldShow;
        };

        getRootNodes().forEach((node) => {
          applyFilter(node);
        });
      };

      const debouncedFilter = debounce(filterTree, 150);
      searchInput.addEventListener('input', debouncedFilter);
      filterTree();
      container.dataset.categoryFilterInitialized = 'true';
    });
  };

  document.addEventListener('DOMContentLoaded', () => {
    initDynamicFilters();
    initFilterToggles();
    registerAutoUpdate();
    initCategoryFilterSearch();
    const shoppingTabModal = document.getElementById('shoppingTabSelectionModal');
    if (shoppingTabModal) {
      const modalContent = shoppingTabModal.querySelector('#shopping-tab-selection-modal-content');
      const defaultMarkup = modalContent ? modalContent.innerHTML : '';
      shoppingTabModal.addEventListener('hidden.bs.modal', () => {
        if (modalContent) {
          modalContent.innerHTML = defaultMarkup;
        }
      });
    }
  });

  const shouldEnhance = (target) => {
    if (!target) {
      return false;
    }
    return ['supplier-filter-container', 'manufacturer-filter-container'].includes(target.id);
  };

  document.body.addEventListener('htmx:afterSwap', (event) => {
    if (event.target && event.target.id === 'filters-update-sink') {
      initDynamicFilters();
      initFilterToggles();
      registerAutoUpdate();
      initCategoryFilterSearch();
    }
  });

  document.body.addEventListener('htmx:oobAfterSwap', (event) => {
    if (shouldEnhance(event.detail && event.detail.target)) {
      initDynamicFilters();
    }
    initFilterToggles();
    registerAutoUpdate();
    initCategoryFilterSearch();
  });
</script>
{% endblock %}